import type { FailureCluster, SkillDiagnosis, SkillEvalResult, SkillFailureCase, SkillProposal } from './types.js'

export interface ProposalReportInput {
  readonly proposal: SkillProposal
  readonly failures?: readonly SkillFailureCase[]
  readonly clusters?: readonly FailureCluster[]
  readonly diagnosis?: SkillDiagnosis
  readonly evaluation?: SkillEvalResult
}

/** Render a stable Markdown review artifact for a proposal and its evidence. */
export function renderProposalMarkdown(input: ProposalReportInput): string {
  const { proposal, failures = [], clusters = [], diagnosis, evaluation } = input
  const addressed = new Set(proposal.evidenceEventIds ?? [])
  const relatedFailures = failures.filter(failure => failure.evidenceEventIds.some(id => addressed.has(id)))
  const cluster = proposal.clusterId === undefined ? undefined : clusters.find(item => item.id === proposal.clusterId)
  const lines = [
    `# Skill Proposal: ${proposal.skillName}`,
    '',
    `- Proposal: \`${proposal.id}\``,
    `- Base version: \`${proposal.baseVersion}\``,
    `- Base hash: \`${proposal.expectedBase.contentHash}\``,
    `- Candidate version: \`${proposal.proposedVersion}\``,
    `- Status: \`${proposal.status}\``,
    `- Generated by: \`${proposal.generatedBy}\``,
    '',
    '## Intent',
    '',
    proposal.intent,
    '',
    '## Observed failures',
    '',
  ]
  if (relatedFailures.length === 0) lines.push('- No linked failure cases.')
  else for (const failure of relatedFailures) lines.push(`- \`${failure.id}\` (${failure.severity}${failure.intentSource ? ` · ${failure.intentSource}` : ''}): ${failure.failure}`)
  if (cluster !== undefined) {
    lines.push('', `Cluster: \`${cluster.id}\` (${cluster.occurrenceCount} occurrences)`, `Signature: ${cluster.signature}`)
  }
  if (diagnosis !== undefined) {
    lines.push('', '## Diagnosis', '', `- Root cause: \`${diagnosis.rootCause}\``, `- Operation: \`${diagnosis.proposedOperation}\``, `- Confidence: \`${diagnosis.confidence}\``, '', diagnosis.hypothesis)
  }
  lines.push('', '## Proposed changes', '', '```diff', proposal.diff || '# No content change', '```', '', `- Changed surfaces: ${proposal.changedSurfaces.join(', ') || 'none'}`, `- Known risks: ${proposal.knownRisks.join('; ') || 'none'}`)
  if (evaluation !== undefined) {
    lines.push('', '## Evaluation', '', `- Helpful/pass count: ${evaluation.passed}/${evaluation.total}`, `- Failed cases: ${evaluation.failed}`, `- Unknown cases: ${evaluation.unknown}`, `- Regressions: ${evaluation.regressions.length}`, `- Schema valid: ${evaluation.schemaValid}`, `- Invocation policy unchanged: ${evaluation.invocationPolicyUnchanged}`, `- Gate: **${evaluation.passedGate ? 'passed' : 'rejected'}**`)
    if (evaluation.gateReasons.length > 0) lines.push('', 'Gate reasons:', ...evaluation.gateReasons.map(reason => `- ${reason}`))
  } else {
    lines.push('', '## Evaluation', '', '- Not evaluated yet.')
  }
  return `${lines.join('\n')}\n`
}

export function renderFailuresMarkdown(failures: readonly SkillFailureCase[]): string {
  const lines = ['# Skill Evolution Failures', '', `Total: ${failures.length}`, '']
  if (failures.length === 0) lines.push('No failure cases recorded.')
  else for (const failure of failures) lines.push(`- \`${failure.id}\` **${failure.skillName}** [${failure.severity}${failure.intentSource ? ` · ${failure.intentSource}` : ''}] ${failure.failure}`)
  return `${lines.join('\n')}\n`
}
