import type { FailureCluster, SkillDiagnosis, SkillEvalResult, SkillFailureCase, SkillProposal } from './types.js'
import type { CorrectionPattern, SkillProposal as ProposalRecord } from './types.js'
import { assessPattern, DEFAULT_CORRECTION_POLICY, type CorrectionPolicy } from './correction.js'

export interface ProposalReportInput {
  readonly proposal: SkillProposal
  readonly failures?: readonly SkillFailureCase[]
  readonly clusters?: readonly FailureCluster[]
  readonly diagnosis?: SkillDiagnosis
  readonly evaluation?: SkillEvalResult
}

/** Render a stable Markdown review artifact for a proposal and its evidence. */
export function renderProposalMarkdown(input: ProposalReportInput): string {
  const { proposal, failures = [], clusters = [], diagnosis, evaluation } = input
  const addressed = new Set(proposal.evidenceEventIds ?? [])
  const relatedFailures = failures.filter(failure => failure.evidenceEventIds.some(id => addressed.has(id)))
  const cluster = proposal.clusterId === undefined ? undefined : clusters.find(item => item.id === proposal.clusterId)
  const lines = [
    `# Skill Proposal: ${proposal.skillName}`,
    '',
    `- Proposal: \`${proposal.id}\``,
    `- Base version: \`${proposal.baseVersion}\``,
    `- Base hash: \`${proposal.expectedBase.contentHash}\``,
    `- Candidate version: \`${proposal.proposedVersion}\``,
    `- Status: \`${proposal.status}\``,
    `- Generated by: \`${proposal.generatedBy}\``,
    '',
    '## Intent',
    '',
    proposal.intent,
    '',
    '## Observed failures',
    '',
  ]
  if (relatedFailures.length === 0) lines.push('- No linked failure cases.')
  else for (const failure of relatedFailures) lines.push(`- \`${failure.id}\` (${failure.severity}${failure.intentSource ? ` · ${failure.intentSource}` : ''}): ${failure.failure}`)
  if (cluster !== undefined) {
    lines.push('', `Cluster: \`${cluster.id}\` (${cluster.occurrenceCount} occurrences)`, `Signature: ${cluster.signature}`)
  }
  if (diagnosis !== undefined) {
    lines.push('', '## Diagnosis', '', `- Root cause: \`${diagnosis.rootCause}\``, `- Operation: \`${diagnosis.proposedOperation}\``, `- Confidence: \`${diagnosis.confidence}\``, '', diagnosis.hypothesis)
  }
  lines.push('', '## Proposed changes', '', '```diff', proposal.diff || '# No content change', '```', '', `- Changed surfaces: ${proposal.changedSurfaces.join(', ') || 'none'}`, `- Known risks: ${proposal.knownRisks.join('; ') || 'none'}`)
  if (evaluation !== undefined) {
    lines.push('', '## Evaluation', '', `- Helpful/pass count: ${evaluation.passed}/${evaluation.total}`, `- Failed cases: ${evaluation.failed}`, `- Unknown cases: ${evaluation.unknown}`, `- Regressions: ${evaluation.regressions.length}`, `- Schema valid: ${evaluation.schemaValid}`, `- Invocation policy unchanged: ${evaluation.invocationPolicyUnchanged}`, `- Gate: **${evaluation.passedGate ? 'passed' : 'rejected'}**`)
    if (evaluation.gateReasons.length > 0) lines.push('', 'Gate reasons:', ...evaluation.gateReasons.map(reason => `- ${reason}`))
    lines.push('', renderCostMarkdown(evaluation.cost))
  } else {
    lines.push('', '## Evaluation', '', '- Not evaluated yet.')
  }
  return `${lines.join('\n')}\n`
}

function formatMetric(metric: { readonly status: string; readonly relativeChange?: number; readonly pValue?: number }): string {
  if (metric.status === 'no-data') return 'no data'
  if (metric.status === 'not-applicable') return 'not applicable'
  return `change ${metric.relativeChange ?? 0}; p=${metric.pValue ?? 'n/a'}`
}

function renderCostMarkdown(cost: SkillEvalResult['cost']): string {
  if (cost === undefined) return 'Execution cost: not recorded'
  const lines = ['## Execution cost', '', `- Estimator: \`${cost.context.estimator}\``, `- Catalog context: ${cost.context.base.catalogTokens} -> ${cost.context.candidate.catalogTokens} (delta ${cost.context.delta.catalogTokens})`, `- Load context: ${cost.context.base.loadTokens} -> ${cost.context.candidate.loadTokens} (delta ${cost.context.delta.loadTokens})`, '', '| Category | Base pass rate | Candidate pass rate | Steps | Tokens |', '| --- | ---: | ---: | --- | --- |']
  for (const category of ['original-failure', 'historical-success', 'boundary'] as const) {
    const item = cost.categories[category]
    lines.push(`| ${category} | ${item.passRate.base} | ${item.passRate.candidate} | ${formatMetric(item.steps)} | ${formatMetric(item.tokens)} |`)
  }
  lines.push('', '### Cost checks', '')
  for (const check of cost.checks) lines.push(`- \`${check.id}\` **${check.status}**: ${check.detail}`)
  if (cost.unstable.length > 0) lines.push('', 'Unstable samples:', ...cost.unstable.map(item => `- \`${item.caseId}\` ${item.exposure}: pass rate ${item.passRate}`))
  return lines.join('\n')
}

export interface CorrectionReportInput {
  readonly episodes?: number
  readonly recognizerVersion?: string
  readonly classifierFailures?: number
  readonly patterns?: readonly CorrectionPattern[]
  readonly proposals?: readonly ProposalRecord[]
  readonly policy?: CorrectionPolicy
  readonly now?: string
}

export function renderFailuresMarkdown(failures: readonly SkillFailureCase[], correction: CorrectionReportInput = {}): string {
  const lines = ['# Skill Evolution Failures', '', `Total: ${failures.length}`, '']
  if (failures.length === 0) lines.push('No failure cases recorded.')
  else for (const failure of failures) lines.push(`- \`${failure.id}\` **${failure.skillName}** [${failure.severity}${failure.intentSource ? ` · ${failure.intentSource}` : ''}] ${failure.failure}`)
  if (correction.patterns !== undefined) {
    const policy = correction.policy ?? DEFAULT_CORRECTION_POLICY
    const now = correction.now ?? new Date().toISOString()
    lines.push('', '## Self-corrections', '', `Policy: \`${policy.version}\` (N=${policy.minFailures}, K=${policy.minSessions}, D=${policy.windowDays}d); recognizer: ${correction.recognizerVersion ?? 'none'}; episodes: ${correction.episodes ?? 0}; classifier failures: ${correction.classifierFailures ?? 0}; now: ${now}`, '')
    if (correction.patterns.length === 0) lines.push('No correction patterns recorded.')
    for (const pattern of correction.patterns) {
      const assessed = assessPattern({ pattern, policy, now, proposals: correction.proposals })
      const reason = assessed.candidate ? 'candidate' : assessed.candidateReason ?? 'blocked'
      lines.push(`- \`${pattern.id}\` ${pattern.intent} | ${pattern.errorSignature} | ${pattern.correction.join(', ') || 'retry'} | ${assessed.windowSessionCount}/${policy.minSessions} since ${assessed.since} | ${reason} | target: ${assessed.promotedSkill ?? 'undecided'}`)
    }
  }
  return `${lines.join('\n')}\n`
}

/** Render an evaluation without requiring a proposal record (useful for CLI output). */
export function renderEvaluationMarkdown(evaluation: SkillEvalResult): string {
  const lines = ['## Evaluation', '', `- Candidate: \`${evaluation.candidateId}\``, `- Gate: **${evaluation.passedGate ? 'passed' : 'rejected'}**`, `- Pass rate: ${evaluation.passed}/${evaluation.total}`, '']
  lines.push('', renderCostMarkdown(evaluation.cost))
  return `${lines.join('\n')}\n`
}
